<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>FakeLDB</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <Target Name="CopyHelpers" AfterTargets="Build">
    <Copy SourceFiles="$(MSBuildProjectDirectory)\mode6helper.exe"
          DestinationFolder="$(OutputPath)"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\mode7helper.exe"
          DestinationFolder="$(OutputPath)"
          SkipUnchangedFiles="true"
          Condition="Exists('$(MSBuildProjectDirectory)\mode7helper.exe')" />
  </Target>
</Project>
