<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>WdpMgr</AssemblyName>
    <RootNamespace>WdpMgr</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="7.0.2" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="app.ico" />
  </ItemGroup>
</Project>
